version: "2.3"
services:
  tensorflow_2_9:
    build: .
    image: tensorflow_2_9
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    shm_size: "8gb"
    ulimits:
      memlock: -1
      stack: 67108864
    stdin_open: true
    privileged: true
    tty: true
    network_mode: "host"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
