version: '3.9'

services:

    nobel_jazzy_rqt_gui:
        image: ghcr.io/ipa-vsp/docker_envs:jazzy
        user: admin:1001
        stdin_open: true
        privileged: true
        tty: true
        network_mode: "host"
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - /etc/localtime:/etc/localtime:ro
            - /tmp/.docker.xauth:/tmp/.docker.xauth
            - $HOME/.Xauthority:/root/.Xauthority
            - ../../../colcon_rqt_ws/src:/home/admin/colcon_ws/src
        environment:
            - DISPLAY=$DISPLAY
            - ROS_DOMAIN_ID=73
        entrypoint: /usr/local/bin/scripts/workspace-entrypoint.sh
        command: tail -f /dev/null # bash -c "top"
