ARG BASE_IMAGE=prachandabhabu/env:melodic-robot

FROM ${BASE_IMAGE}

RUN useradd -ms /bin/bash kuka
USER kuka
WORKDIR /home/kuka

RUN mkdir -p catkin_ws/src && cd ~/catkin_ws/src \
    && git clone -b v1.0 --recurse-submodules https://github.com/LernFabrik/kuka_iiwa7_ros.git

RUN rosdep update
RUN cd ~/catkin_ws \
    && rosdep install --ignore-src --from-paths src -y

COPY ./vscode.sh ./

#RUN chmod +x ./vscode.sh
#RUN ./vscode.sh

# ENTRYPOINT ["top", "-b"]
# CMD ["-c"]
