ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Install Extra dependencies
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
        ros-${ROS_DISTRO}-gazebo-ros \
        ros-${ROS_DISTRO}-gazebo-ros2-control \
        ros-${ROS_DISTRO}-gazebo-plugins \
        ros-${ROS_DISTRO}-gazebo-msgs \
&& rm -rf /var/lib/apt/lists/* \
&& apt-get clean
