name: ROS2 Images for KUKA

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    # branches: [ main ]
    paths:
      - 'dockerhub/kuka/**'
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/build_env

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: dockerhub/kuka/Dockerfile
          path: dockerhub/kuka
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/build_env:ros2-humble-kuka
          labels: ${{ steps.meta.outputs.labels }}
