# This is a basic workflow to help you get started with Actions

name: Pytorch with Detectron2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    # branches: [ main ]
    paths:
      - 'dockerhub/pytorch_1_10/**'
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - {TORCH_VERSION: 1_10_0}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/build_env
          tag: pytorch-${{ matrix.env.TORCH_VERSION }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: dockerhub/pytorch_1_10/Dockerfile
          path: dockerhub/pytorch_1_10
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/build_env:pytorch-${{ matrix.env.TORCH_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
