version: '3'

services:
  ros-melodic-base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: melodic-base

  melodic-kinect:
    build:
      context: .
      dockerfile: Dockerfile.kinect
      args:
        - BASE_IMAGE=melodic-base
    image: melodic-kinect
    # runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
    stdin_open: true
    privileged: true
    tty: true
    network_mode: "host"
    volumes:
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/root/.Xauthority
    command:
      - k4aviewer
