version: '3.9'

services:
    humble_test:
        image: humble_jammy:test
        user: admin:1000
        stdin_open: true
        privileged: true
        tty: true
        network_mode: "host"
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - /etc/localtime:/etc/localtime:ro
            - ../../../colcon_can_ws/src:/home/admin/colcon_ws/src
        environment:
            - DISPLAY=$DISPLAY
            - ROS_DOMAIN_ID=73
        entrypoint: /usr/local/bin/scripts/workspace-entrypoint.sh
        command: tail -f /dev/null # bash -c "top"

    nobel_rolling_canopen_test:
        image: rolling_noble:canopen
        user: admin:1000
        stdin_open: true
        privileged: true
        tty: true
        network_mode: "host"
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - /etc/localtime:/etc/localtime:ro
            - ../../../colcon_can_ws/src:/home/admin/colcon_ws/src 
        environment:
            - DISPLAY=$DISPLAY
            - ROS_DOMAIN_ID=73
        entrypoint: /usr/local/bin/scripts/workspace-entrypoint.sh
        command: tail -f /dev/null # bash -c "top"

    nobel_rolling_opcua_test:
        image: rolling_noble:opcua
        user: admin:1000
        stdin_open: true
        privileged: true
        tty: true
        network_mode: "host"
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - /etc/localtime:/etc/localtime:ro
            - ../../../colcon_opcua_ws/src:/home/admin/colcon_ws/src
        environment:
            - DISPLAY=$DISPLAY
            - ROS_DOMAIN_ID=73
        entrypoint: /usr/local/bin/scripts/workspace-entrypoint.sh
        command: tail -f /dev/null # bash -c "top"

    iron_test:
        image: canopen_iron:test
        user: admin:1000
        stdin_open: true
        privileged: true
        tty: true
        network_mode: "host"
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - /etc/localtime:/etc/localtime:ro
            - ../../../colcon_can_ws/src:/home/admin/colcon_ws/src
        environment:
            - DISPLAY=$DISPLAY
            - ROS_DOMAIN_ID=73
        entrypoint: /usr/local/bin/scripts/workspace-entrypoint.sh
        command: tail -f /dev/null # bash -c "top"
