version: '3.9'

services:
    x86_64:
        build:
            context: .
            dockerfile: Dockerfile.base
        image: x86_64

    x86_64.humble:
        depends_on:
            - x86_64
        build:
            context: .
            dockerfile: Dockerfile.humble
            args:
                - BASE_IMAGE=x86_64
        image: x86_64.humble

    x86_64.humble.gazebo:
        depends_on:
            - x86_64.humble
        build:
            context: .
            dockerfile: Dockerfile.gazebo
            args:
                - BASE_IMAGE=x86_64.humble
        image: x86_64.humble.gazebo

    x86_64.humble.gazebo.moveit:
        depends_on:
            - x86_64.humble.gazebo
        build:
            context: .
            dockerfile: Dockerfile.moveit
            args:
                - BASE_IMAGE=x86_64.humble.gazebo
        image: x86_64.humble.gazebo.moveit

    x86_64.humble.gazebo.moveit.user:
        depends_on:
            - x86_64.humble.gazebo.moveit
        build:
            context: .
            dockerfile: Dockerfile.user
            args:
                - BASE_IMAGE=x86_64.humble.gazebo.moveit
        image: x86_64.humble.gazebo.moveit.user
        user: admin:1000
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
        stdin_open: true
        privileged: true
        tty: true
        network_mode: "host"
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - /etc/localtime:/etc/localtime:ro
            # - ../../src:/home/admin/colcon_ws/src
        environment:
            - DISPLAY=$DISPLAY
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
        entrypoint: /usr/local/bin/scripts/workspace-entrypoint.sh
        command: tail -f /dev/null # bash -c "top"
