version: '3.8'

services:
  qemu-user-static:
    image: multiarch/qemu-user-static:latest
    privileged: true
    command: ["--reset", "-p", "yes"]

  rosdeb:
    build:
      context: .
      dockerfile: Docker/runtime.Dockerfile
      args:
        - BASE_IMAGE=arm64v8/ubuntu:22.04
    image: arm64v8/ubuntu:jammy
    platform: linux/arm64
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /lib/modules:/lib/modules:rw
      - ~/ros_ws/ctrlx-automation-sdk:/ros_ws/
    tmpfs:
      - /run
      - /run/lock
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse:/dev/fuse"
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
    command: ["/bin/bash", "-c", "install_snap_deps.sh"]
    stdin_open: true
    tty: true

# volumes:
#   ros_ws:
