#!/bin/bash

export PATH=/snap/bin:$PATH
export SNAPCRAFT_BUILD_ENVIRONMENT="host"
echo SNAPCRAFT_BUILD_ENVIRONMENT=$SNAPCRAFT_BUILD_ENVIRONMENT >> /etc/environment
export SNAPCRAFT_ENABLE_EXPERIMENTAL_TARGET_ARCH=1
echo SNAPCRAFT_ENABLE_EXPERIMENTAL_TARGET_ARCH=$SNAPCRAFT_ENABLE_EXPERIMENTAL_TARGET_ARCH >> /etc/environment
export SNAPCRAFT_BUILD_INFO=1
export PYTHONPATH=/snap/snapcraft/current/lib/python3.10/site-packages/:$PYTHONPATH

$@
