# This is a basic workflow to help you get started with Actions

name: ROS2 Images

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    # branches: [ main ]
    paths:
      - 'dockerhub/ros2_ci_build/**'
  # pull_request:
  #   branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: humble}
          - {ROS_DISTRO: iron}
          - {ROS_DISTRO: rolling}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/build_env

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: dockerhub/ros2_ci_build/Dockerfile
          push: true
          build-args: |
            ROS_DISTRO=${{ matrix.env.ROS_DISTRO }}
          tags: ${{ secrets.DOCKER_USERNAME }}/build_env:${{ matrix.env.ROS_DISTRO }}
          labels: ${{ steps.meta.outputs.labels }}
