# This is a basic workflow to help you get started with Actions

name: ROS2 Images

on:
  push:
    paths:
      - 'creator/**'
  schedule:
    - cron: '0 0 * * 0'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME:  ${{ github.repository }}

jobs:
  push_to_registry:
    name: Push Docker image to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: rolling, OS_VERSION: 24.04}
          - {ROS_DISTRO: jazzy, OS_VERSION: 24.04}
          - {ROS_DISTRO: humble, OS_VERSION: 22.04}
          - {ROS_DISTRO: noetic, OS_VERSION: 20.04}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          chmod +x creator/scripts/run_env.sh
          chmod +x creator/scripts/build_image.sh
          ./creator/scripts/run_env.sh -o ${{ matrix.env.OS_VERSION }} -v ${{ matrix.env.ROS_DISTRO }} -u skip -i ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.env.ROS_DISTRO }} -b

      - name: List Docker images
        run: docker images

      - name: Push Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.env.ROS_DISTRO }}

  push_to_registry_manipulation:
    needs: push_to_registry
    name: Push Docker image MOVEIT to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: rolling, OS_VERSION: 24.04}
          - {ROS_DISTRO: jazzy, OS_VERSION: 24.04}
          - {ROS_DISTRO: humble, OS_VERSION: 22.04}
          - {ROS_DISTRO: noetic, OS_VERSION: 20.04}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          chmod +x creator/scripts/run_env.sh
          chmod +x creator/scripts/build_image.sh
          ./creator/scripts/run_env.sh -o ${{ matrix.env.OS_VERSION }} -v ${{ matrix.env.ROS_DISTRO }} -u manipulation -i ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.env.ROS_DISTRO }}_moveit -b

      - name: List Docker images
        run: docker images

      - name: Push Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.env.ROS_DISTRO }}_moveit

  push_to_registry_navigation:
    needs: push_to_registry
    name: Push Docker image NAVIGATION to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: rolling, OS_VERSION: 24.04}
          - {ROS_DISTRO: jazzy, OS_VERSION: 24.04}
          - {ROS_DISTRO: humble, OS_VERSION: 22.04}
          - {ROS_DISTRO: noetic, OS_VERSION: 20.04}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          chmod +x creator/scripts/run_env.sh
          chmod +x creator/scripts/build_image.sh
          ./creator/scripts/run_env.sh -o ${{ matrix.env.OS_VERSION }} -v ${{ matrix.env.ROS_DISTRO }} -u navigation -i ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.env.ROS_DISTRO }}_nav2 -b

      - name: List Docker images
        run: docker images

      - name: Push Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.env.ROS_DISTRO }}_nav2
