# This is a basic workflow to help you get started with Actions

name: ROS2 Images

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    # paths:
    #   - 'dockerhub/ros2_ci_build/**'
  # pull_request:
  #   branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME:  ${{ github.repository }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push_to_registry:
    name: Push Docker image to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        ros_distro: [ rolling, jazzy, iron, humble, isaachumble, noetic, kinetic ]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          chmod +x creator/scripts/run_env.sh
          chmod +x creator/scripts/build_image.sh
          ./creator/scripts/run_env.sh -o 24.04 -v ${{ matrix.ros_distro }} -u skip -i ${{ env.IMAGE_NAME }}:${{ matrix.ros_distro }} -b

      - name: Push Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.ros_distro }}
