services:
  mp0700-6.0.1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: admin
        USER_UID: "${UID}"
        USER_GID: "${GID}"
    container_name: mp0700-6.0.1
    entrypoint: /usr/local/bin/scripts/workspace-entrypoint.sh
    stdin_open: true
    tty: true
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
    network_mode: host
    ipc: host
    environment:
      TZ: "Europe/Berlin"
      DISPLAY: "${DISPLAY}"
      QT_X11_NO_MITSHM: "1"
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "all"
      ROS_LOCALHOST_ONLY: "0"
    volumes:
      - /home/ipa326/workspace/ros_ws/fullbody/colcon_rox_ws/src:/home/admin/colcon_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: tail -f /dev/null
